spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      auto-commit: false
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
sfn:
  wms:
    url: http://ss-wms-dev.ndev.sfn.local
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:Demo;MODE=MySQL;DB_CLOSE_DELAY=-1;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        connection:
          provider_disables_autocommit: false
        show_sql: true
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      maximum-pool-size: 5
      auto-commit: false
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        connection:
          provider_disables_autocommit: false
        show_sql: true

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: prod