spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      auto-commit: false
    url: jdbc:mysql://localhost:3306/fs_invoicing?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      maximum-pool-size: 5
      auto-commit: false
    url: jdbc:mysql://localhost:3306/fs_invoicing?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver