spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - infra
  application:
    name: multi-module-api

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: ERROR
    org:
      hibernate:
        type:
          descriptor:
            sql: info

---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8001

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: prod